### ISSUE TITLE
Custom query tag, locale mapping [enhancement]

### ISSUE THREAD

**Issue by wq9578** [bezhanSalleh/filament-language-switch#103]
Two simple enhancements would be desirable.
The language switcher [retrieves information](https://github.com/bezhanSalleh/filament-language-switch/blob/e4674eed43ac460ca40ecdd6cfe9e1d7275267e4/src/LanguageSwitch.php#L261) from the query tag `locale`, with the browser request as fallback.

1. Instead of only offering the query tag `locale`, alternatives should be configurable, for example:
```
LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
            $switch
                ->locales(['ar','en','fr','en_GB']) // also accepts a closure
                ->tag('lc');
        });
```
Then `mywebsite.com/mypage/myresource/123?locale=en_GB` is reduced to `mywebsite.com/mypage/myresource/123?lc=en_GB`.

2. A mapping to more handier locale codes should be configurable, for example:
```
LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
            $switch
                ->locales(['ar','en','fr','en_GB']) // also accepts a closure
                ->tag('lc')
                ->mapping(['uk' => 'en_GB', 'pt' => 'pt_PT']);
        });
```
Then `mywebsite.com/mypage/myresource/123?lc=en_GB` is further reduced to `mywebsite.com/mypage/myresource/123?lc=uk`.

Some links:
- [Laravel using ISO 15897](https://laravel.com/docs/11.x/localization#using-short-keys)
  > For languages that differ by territory, you should name the language directories according to the ISO 15897. For example, "en_GB" should be used for British English rather than "en-gb".
- Short custom localization code `uk` used by Apple in URL path: https://www.apple.com/uk/iphone/
- Sample language file for [pt_PT](https://github.com/filamentphp/filament/blob/c343615bd0544959ab830cae902c9b37bc238249/packages/panels/resources/lang/pt_PT/pages/auth/login.php#L5)
- Sample language file for [pt_BR](https://github.com/filamentphp/filament/blob/c343615bd0544959ab830cae902c9b37bc238249/packages/panels/resources/lang/pt_BR/pages/auth/login.php#L5)

**Comment by bezhanSalleh** [comment]
the plugin just switches the user or app local and how you handle the translatable routes is totally different.
