### ISSUE TITLE
 Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found. 

### ISSUE THREAD

**Issue by ateframadan-diverge** [bezhanSalleh/filament-language-switch#104]
installing along side [filament-shield](https://github.com/bezhansalleh/filament-shield) causes this error
`` Svg by name "filament-shield::filament-shield.nav.role.icon" from set "default" not found. ``

**Comment by ateframadan-diverge** [comment]
I'm using Filament version 3.2.
the package was stopping the translations to be loaded.
quick play around is to add the middleware (``\BezhanSalleh\FilamentLanguageSwitch\Http\Middleware\SwitchLanguageLocale::class``) to ``app/Providers/Filament/AdminPanelProvider.php`` before ``DispatchServingFilamentEvent::class`` 

and replace

`
Filament::serving(function () {
    LanguageSwitch::boot();
});
`

with
`
Event::listen(ServingFilament::class, function () {
    LanguageSwitch::boot();
});
`

in the package's ``FilamentLanguageSwitchServiceProvider``

**Comment by bezhanSalleh** [comment]
Can't reproduce. Could you Submit a repro repo. I'll have a look. Thanks
