### ISSUE TITLE
Pluralization Language

### ISSUE THREAD

**Issue by fernandoparada18** [bezhanSalleh/filament-language-switch#105]
It would be useful to improve pluralization when changing to a language other than English, or at least improve it in the [languages ​​currently supported by the Laravel pluralizer](https://laravel.com/docs/11.x/localization#pluralization-language), which are: French, Norwegian-Bokmal, Portuguese, Spanish, Turkish. And if it is not supported, leave English as the default.

**Comment by bezhanSalleh** [comment]
The main functionality of the plugin is to toggle your apps locale. how the app's localization system works is up to the dev.

**Comment by fernandoparada18** [comment]
I was able to do it by using a listener for the` BezhanSalleh\FilamentLanguageSwitch\Events\LocaleChanged` event
