### ISSUE TITLE
Not working outside panel

### ISSUE THREAD

**Issue by nmortezamt** [bezhanSalleh/filament-language-switch#107]
I have a login page that I want to support multiple languages.
I followed the documentation and used this code

```
LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
            $switch
                ->visible(outsidePanels: true)
                ->outsidePanelRoutes(['login'])
                ->locales(['en','tr'])
                ->outsidePanelPlacement(Placement::TopRight)
                ->flags([
                    'tr' => asset('assets/flags/tr.svg'),
                    'en' => asset('assets/flags/us.svg'),
                ])->circular()
            ;
        });
```

in boot method service provider

**Comment by KSneijders** [comment]
@nmortezamt The default routes for `->outsidePanelRoutes()` are:

```php
[
    'auth.login',
    'auth.profile',
    'auth.register',
]
```

So if you don't mind having it on the `'auth.profile'` and `'auth.register'` pages as well, you could remove your `['login']` argument and just leave it as:

```
    ->outsidePanelRoutes()
```

Otherwise, you should probably change  it to:

```
    ->outsidePanelRoutes(['auth.login'])
```

**Comment by kerwin-wildsea** [comment]
@nmortezamt The default routes for `->outsidePanelRoutes()` are:

```php
[
    'auth.login',
    'auth.profile',
    'auth.register',
]
```

So if you don't mind having it on the `'auth.profile'` and `'auth.register'` pages as well, you could remove your `['login']` argument and just leave it as:

```
    ->outsidePanelRoutes()
```

Otherwise, you should probably change  it to:

```
    ->outsidePanelRoutes(['auth.login'])
```

**Comment by nmortezamt** [comment]
@kerwin-wildsea It didn't work again

**Comment by kerwin-wildsea** [comment]
> @kerwin-wildsea It didn't work again

Not a very helpful response, could you provide:

1. Can you show the code you're currently using? 
2. Can you show the route you're on when logging in? `dd(request()->route()->getName())`

**Comment by nmortezamt** [comment]
@kerwin-wildsea 
Excuse me, can you give me a sample code, for example, I have a home page. How to display this package on this page.
I went through all the steps in the document.

**Comment by kerwin-wildsea** [comment]
@nmortezamt The code you sent earlier is all you need. I copied it over and it is working fine (besides the flags, but I don't have the assets). The only thing I can think of is that you haven't placed the code in the right provider?

Either of: 
- `app/Providers/AppServiceProvider::boot` (For all panels)
- `app/Providers/Filament/AdminPanelProvider::boot` (Any specific panel you like to register it in)

**Comment by kerwin-wildsea** [comment]
@nmortezamt The code you sent earlier is all you need. I copied it over and it is working fine (besides the flags, but I don't have the assets). Is it working on the homepage (After login)? If it is working on the main dashboard (usually [localhost/admin](http://localhost/admin)) it should work on the login page with the code you sent earlier. 

The only thing I can think of that you might have placed the code in the wrong location? 
Either of the two below _should_ just work:
- `app/Providers/AppServiceProvider::boot`
- `app/Providers/Filament/AdminPanelProvider::boot`

I copied your code exactly inside the `AppServiceProvider` `boot` function, and it worked perfectly.
_(Although without missing assets ofc)_
![image](https://github.com/user-attachments/assets/d4c82141-0d77-4ec4-aaba-6c50a8eb62d7)
