### ISSUE TITLE
Component does not work correctly in laravel octane

### ISSUE THREAD

**Issue by medeiroz** [bezhanSalleh/filament-language-switch#12]
Component does not work correctly in laravel octane

When using laravel octane with swoole, the register component not shared with all  server instances

The component has been displayed only 1st access.
On 2nd or *th access  the component is not displaying

![Google-Google-Chrome-2022-11-23-23-35-00](https://user-images.githubusercontent.com/11270546/203681781-c63ffb3a-86a3-401f-97e4-1c92f7696430.gif)

**Comment by bezhanSalleh** [comment]
fixed by #13
