### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by monzer15** [bezhanSalleh/filament-language-switch#17]
Laravel version: 8.83.27
Filament version: 2.16.66

Problem 1
    - bezhansalleh/filament-language-switch[v1.0.0, ..., 1.0.5] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded,
likely because it conflicts with another require.
    - Root composer.json requires bezhansalleh/filament-language-switch ^1.0 -> satisfiable by bezhansalleh/filament-language-switch[v1.0.0, ..., 1.0.5].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bezhansalleh/filament-language-switch:*" to figure out if any version is instal
lable, or "composer require bezhansalleh/filament-language-switch:^2.1" if you know which you need.

**Comment by EngGemy** [comment]
hello can you ask do you try to translaate the  filament code
