### ISSUE TITLE
Is it possible to customize location of the language switcher component?

### ISSUE THREAD

**Issue by thomas-alrek** [bezhanSalleh/filament-language-switch#29]
I know that I can easily customize the apperance of the language switcher component by exporting the view.
However, what I'm not able to figure out, is how I can customize where in the app that component is located.
I would very much like to move the language switcher into e.g. the users drop down menu, or to a separate settings resource view.

Is this possible at all?

**Comment by bezhanSalleh** [comment]
cool idea, right now its hardcoded in that hook, but you can PR to change where to render it based on the available hooks in filament
