### ISSUE TITLE
Feature Request: Hook to do more when switching language

### ISSUE THREAD

**Issue by ziming** [bezhanSalleh/filament-language-switch#33]
Sometimes after doing an action, i want to send some notifications in the user preferred locale. However notifications are typically delayed queue jobs.

So it will be good if you provide hooks such that when switch locale, i can set the auth user locale value in the database to the new value.

See:
https://laravel.com/docs/10.x/notifications#user-preferred-locales

**Comment by bezhanSalleh** [comment]
nice, right now not possible but you can PR it and I will merge.
