### ISSUE TITLE
Not Working with the filament-companies plugin when user signed out

### ISSUE THREAD

**Issue by alkoumi** [bezhanSalleh/filament-language-switch#35]
## Thank you brother for this amazing plugin

I am using your plugin in my project in RTL Direction, it works perfectly when the user is authenticated, But when the user logout from the application it shows all authentication views in the LTR direction 🧐 it is supposed to be in the RTL

I am using this plugin for authentication [https://github.com/andrewdwallo/filament-companies](https://github.com/andrewdwallo/filament-companies).

## I appreciate your help brother  🤝

**Comment by alkoumi** [comment]
The  [https://github.com/andrewdwallo/filament-companies](https://github.com/andrewdwallo/filament-companies). uses Laravel Fortify for authentication

**Comment by bezhanSalleh** [comment]
This plugin only changes the locale not locale direction. If the admin panel works fine then the custom views used in the other package might have an issue on not picking up the locale or changing the direction for it.
