### ISSUE TITLE
V2 Switch Not work

### ISSUE THREAD

**Issue by mstfkhazaal** [bezhanSalleh/filament-language-switch#37]
i install v2 in filament 3 
but thw switch not exist in header

**Comment by bezhanSalleh** [comment]
look into the configure section of the readme or the plugin dev on the filamentphp docs

**Comment by mstfkhazaal** [comment]
I searched and found the problem with the hooks
I tried all the hooks in the documentation but they didn't show up at the beginning of the search
https://beta.filamentphp.com/docs/3.x/support/render-hooks

**Comment by bezhanSalleh** [comment]
the render hooks names have been changed since this was implemented to properly align with the new panels system filament offers. just update and everything will be fine.
