### ISSUE TITLE
Change render hook

### ISSUE THREAD

**Issue by LukasFreyCZ** [bezhanSalleh/filament-language-switch#39]
Hi, you might want to change the default render hook to `panels::user-menu.before` instead. 

If you don't use global search, which by default is not enabled in the filament panel, the language switch will not appear, due to `panels::global-search.end` working only if global search is enabled.

**Comment by bezhanSalleh** [comment]
the default hook for the plugin is`panels::global-search.after` so if you are on the stable release there won't be any issue since this hook will work even if the global search is not enabled.
