### ISSUE TITLE
'panels::global-search.after' render hook name not (always) working

### ISSUE THREAD

**Issue by KonradHambuch** [bezhanSalleh/filament-language-switch#44]
@bezhanSalleh 

If I leave $renderHookName as set, nothing shows, but if I change it to other render hooks, it displays there.

for example: 

panels::topbar.end
![image](https://github.com/bezhanSalleh/filament-language-switch/assets/48684304/464da274-2bfd-49ee-a4b7-b904f359cc10)

I think this is beacuse in documentation there is no 'panels::global-search.after', there is 'panels::global-search.end', but that shows language-switch panel **only if** there is a global search component on the panel and looks like this, with no margin:
![image](https://github.com/bezhanSalleh/filament-language-switch/assets/48684304/0b155ba4-f938-46b4-827e-5a3c2756c7ca)

I suggest maybe using 'panels::user-menu.before'? :|

**Comment by bezhanSalleh** [comment]
This hook was added in filament v3. So if you are using v2 use the v1 filament-language-switch.

**Comment by KonradHambuch** [comment]
I use V3, but none of them uses 'after' form global-search component.

V3: https://filamentphp.com/docs/3.x/support/render-hooks#:~:text=panels%3A%3Aglobal%2Dsearch.end
V2 https://filamentphp.com/docs/2.x/admin/appearance#render-hooks:~:text=global%20search%20input-,global%2Dsearch.end,-%2D%20after%20global%20search

**Comment by ibrahimBougaoua** [comment]
**I faced the same problem,there is a simple style issue with others hooks,**
**Use this hook it's work perfectly.**

FilamentLanguageSwitchPlugin::make()
->renderHookName('panels::user-menu.before'),

**Comment by bezhanSalleh** [comment]
@KonradHambuch @ibrahimBougaoua 
These render hooks `panels::global-search.before` & `panels::global-search.after` were created to address a PR i made to fix the design issue. 
So that's how I know you neither of you are on v3.
given that v3 is 2weeks old, it wasn't documented until now.
https://github.com/filamentphp/filament/pull/7762
