### ISSUE TITLE
Use ISO 639-1:2002 Codes for the representation of names of languages

### ISSUE THREAD

**Issue by StanMenten99** [bezhanSalleh/filament-language-switch#45]
Hi,

I noticed that the rounded icons with the short language is not showing as I would expect regarding the ISO 639-1:2002 standard. 

What it is currently (Nederlands (Dutch) is shows as Du):
<img width="241" alt="CleanShot 2023-08-15 at 02 10 03@2x" src="https://github.com/bezhanSalleh/filament-language-switch/assets/26350392/6672ffa9-995a-48ac-b8ec-85397783ddee">

As I would expect (see Nederlands (=Dutch)):
<img width="242" alt="CleanShot 2023-08-15 at 02 10 46@2x" src="https://github.com/bezhanSalleh/filament-language-switch/assets/26350392/6db872fc-6f77-43eb-a5d0-4a5bdeb1a004">

In terms of user experience, this would make more sense I think.

**Comment by bezhanSalleh** [comment]
you are welcome to PR anything that would make UX better just update the codes in the config 🖖
