### ISSUE TITLE
It does not work on filament v3

### ISSUE THREAD

**Issue by aymanalhattami** [bezhanSalleh/filament-language-switch#46]
In AdminPanelProvider 
```
->plugins([
    FilamentLanguageSwitchPlugin::make()
])
```
and nothing appear in the admin panel

![image](https://github.com/bezhanSalleh/filament-language-switch/assets/34315778/8c96d762-b655-4b5c-a1e5-a1384c0a292b)

**Comment by bezhanSalleh** [comment]
Make sure you have important the class `BezhanSalleh\FilamentLanguageSwitch\FilamentLanguageSwitchPlugin;` and actually on v3. Clear your view cache and if you have published filament views republish them.

**Comment by aymanalhattami** [comment]
It worked with me  when I changed the hook to ```panels::user-menu.before```
```
->plugins([
    FilamentLanguageSwitchPlugin::make()->renderHookName('panels::user-menu.before'),
])
```
