### ISSUE TITLE
installation not possible 

### ISSUE THREAD

**Issue by Dontorpedo** [bezhanSalleh/filament-language-switch#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bezhansalleh/filament-language-switch[dev-main, v0.0.0, ..., v0.0.1, v1.0.0, ..., 1.0.1] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bezhansalleh/filament-language-switch * -> satisfiable by bezhansalleh/filament-language-switch[dev-main, v0.0.0, v0.0.1, v1.0.0, 1.0.1, 9999999-dev].

filament 2.x is installed and php 8.0

**Comment by bezhanSalleh** [comment]
from what i can tell your laravel version must be 8 therefore this package doesn't support L8
