### ISSUE TITLE
Can I use this Plugin if I I'm not using the Panel Builder?

### ISSUE THREAD

**Issue by jesusLM94** [bezhanSalleh/filament-language-switch#56]
I'd like to inquire about the ability to use this package when not utilizing the Panel Builder. I have individually installed all the Filament packages (Form Builder, Table Builder, Notifications, etc.) except for the Panel Builder.

Despite reviewing the Readme and various issues in this repository, I couldn't find any information regarding this particular scenario, and my own attempts to make it work have been unsuccessful. Additionally, I read the plugin section in the filament docs, but they appear to be closely tied to Panels.

Is there anyone with experience in this matter who could offer insights or guide me in the right direction?

**Comment by bezhanSalleh** [comment]
it's just a livewire component so i think it would be possible.
try adding this to your nav and see if it works or not `<livewire:switch-filament-language />`
let me know

**Comment by ArashDevelops** [comment]
Thank you for this great package. It works great inside filament panel, for the regular livewire pages I tried this livewire componenet:     <livewire:filament-language-switch /> and unfortunately both ui and functionality broke. anything new on this?
