### ISSUE TITLE
Too big image on iOS

### ISSUE THREAD

**Issue by donatiss** [bezhanSalleh/filament-language-switch#58]
![IMG_0312](https://github.com/bezhanSalleh/filament-language-switch/assets/6832828/5ffb976c-23fc-4059-9a11-53f810d8f374)

iPhone 14, iOS 17.1.1

**Comment by donatiss** [comment]
`.language-switch-trigger {
    > img {
        @apply w-full;
    }
}`

**Comment by bezhanSalleh** [comment]
From the looks of it that's a custom them so you need to check the theme section of the readme.
