### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by aquzif** [bezhanSalleh/filament-language-switch#59]
Hello,
When i try to change language, i get "Component not found" error inside dev tools.

Steps to reporduce:
1. prepare fresh filamentphp setup:
    - `composer create-project laravel/laravel example-app`
    - setup database
    - `composer require filament/filament:"^3.0-stable" -W`
    - `php artisan filament:install --panels`
    - migrate, and create user
2. Install plugin:
    - `composer require bezhansalleh/filament-language-switch`
    - register Language Switch in AppServiceProvider, in boot method as belows:

```php
LanguageSwitch::configureUsing(function (LanguageSwitch $languageSwitch) {
    $languageSwitch->locales([
        'fr', 'en'
    ])->renderHook('panels::global-search.before');
});
```

Note: To even see language switch, i need to change render hook to `global-search.before`, create resource for User, and add `protected static ?string $recordTitleAttribute = 'email';`

Now when I try to change the language I get the error as below

![image](https://github.com/bezhanSalleh/filament-language-switch/assets/67521903/6d55d189-eed3-4636-9b3c-159c1c76cd7b)

**Comment by bezhanSalleh** [comment]
i don't know what, but something is not right. here is the repo created just like the steps you outlined and it works as it should.
https://github.com/bezhanSalleh/filament-language-switch-test

**Comment by aquzif** [comment]
I compared yours files with mine, there was one thing that changed everything: require filament/filament. 
I had "3.0-stable", you had "^3.0". Even if i created clean installation, i didnt had latest version of filament. 
Once i changed this to your version, deleted vendor files, composer lock and redownloaded vendor files, everything started working properly. Thank you for a repository :)
