### ISSUE TITLE
Call to undefined function BezhanSalleh\FilamentLanguageSwitch\locale_get_display_name()

### ISSUE THREAD

**Issue by reubenloma** [bezhanSalleh/filament-language-switch#60]
I don't have any issues in my local system but when I moved to server, I got an error saying `Call to undefined function BezhanSalleh\FilamentLanguageSwitch\locale_get_display_name()`.
Have a look at this [link](https://flareapp.io/share/xmNZpxxm#debug)
I also attach the screenshot. 
![Screenshot from 2023-12-12 13-40-59](https://github.com/bezhanSalleh/filament-language-switch/assets/141895583/190f9097-8f9e-48ae-8de5-2e3f82c82549)
Server configurations:
Apache
PHP8.2
Ubuntu 22.04.3 LTS

**Comment by Ardavan-Shamroshan** [comment]
Hi bro, how did you fix dat?

**Comment by ayoubrachik** [comment]
how did you fix it ??

**Comment by Sabawoon-Khan** [comment]
> how did you fix it ??

how did you fix it ?

**Comment by baijunyao** [comment]
Hi guys, installing the [intl](https://www.php.net/manual/en/book.intl.php) extension can fix this error.

https://stackoverflow.com/questions/48674297/php-intl-extension-in-docker-container
