### ISSUE TITLE
Share locale session  between subdomains

### ISSUE THREAD

**Issue by mstfkhazaal** [bezhanSalleh/filament-language-switch#64]
How can getlocal from blade file in dynamic subdomain?

**Comment by bezhanSalleh** [comment]
could you be a bit more descriptive?

**Comment by mstfkhazaal** [comment]
> could you be a bit more descriptive?

Thank you, the problem has been resolved

My problem was accessing the current language from outside the filament. I got the current language from session('locale'), and added it to the .env file session_domain=.example.com.  Then I executed the composer dump-autoload command and it worked
