### ISSUE TITLE
Detect language from browser (if not logged in)

### ISSUE THREAD

**Issue by wq9578** [bezhanSalleh/filament-language-switch#65]
It would be desirable to have the language detected from the browser setting, if not logged in, as done [here](https://github.com/mcamara/laravel-localization).

If logged in, the user locale should be stored in the database, as somebody already [suggested](https://github.com/bezhanSalleh/filament-language-switch/issues/62) earlier.

**Comment by bezhanSalleh** [comment]
It already does, if the user locale is one of the locales you have enabled for the switch.

**Comment by wq9578** [comment]
There is a bug, so it doesn't work in most cases: https://github.com/bezhanSalleh/filament-language-switch/issues/68
