### ISSUE TITLE
Language Switch is not visible when there are multiple panels

### ISSUE THREAD

**Issue by torgodly** [bezhanSalleh/filament-language-switch#67]
I have encountered an issue with the Language Switch feature in the Filament package. The package includes a feature that renders a button for switching the language of the system, and it works fine when there is a single panel. However, when multiple panels are created, the Language Switch button is not visible.

Upon further investigation, I found that the button becomes visible only after explicitly setting the **outsidePanelRoutes** and assigning them to the panel route. Even then, a new problem arises – the button renders on top of either the avatar or the application name in Filament.

**Steps to Reproduce:**

1. Create multiple panels using .
2. Observe that the Language Switch button is not visible by default.
3. Set **outsidePanelRoutes** and assign them to the panel route.
4. Notice that the Language Switch button now renders on top of either the avatar or the application name.

**Comment by bezhanSalleh** [comment]
You have might have Miss configured something. And the outside panels option is for routes like profile, login, ...etc. could you show me how have you configured the plugin and where?
