### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by aeq-dev** [bezhanSalleh/filament-language-switch#7]
Hello,
Thanks for this nice package,
I've successfully installed it, and I've enabled flag, but I got this error 
`Unable to locate a class or view for component [flag-1x1-us].`
How can I install flag-icons ? I tried installed it via npm but I don't know how to configure it with my fresh laravel project and filament
Thanks :)

**Comment by aeq-dev** [comment]
Never mind, I did it :)

**Comment by Odilbukh** [comment]
@aeq-dev How did you fix it? I have same issue

**Comment by aeq-dev** [comment]
@Odilbukh 
In the config file flag field, he mentioned it, install this : composer require stijnvanouplines/blade-country-flags
