### ISSUE TITLE
Updating from version 2 to 3, install issues

### ISSUE THREAD

**Issue by terjelundemotangen** [bezhanSalleh/filament-language-switch#71]
Updating from version 2 to 3.

I get this result:
Filament\Support\Components\ComponentManager::configure(): Argument #1 ($component) must be of type Filament\Support\Components\Component, BezhanSalleh\FilamentLanguageSwitch\LanguageSwitch given

"filament/filament": "^3.0-stable", Laravel 10.40

Is there anything I can do to fix this?

**Comment by Saifallak** [comment]
+1

**Comment by bezhanSalleh** [comment]
The issue is due to a change in the latest filament release itself, you can lock your filament versions to 3.1.37 for time being and a fix will be released soon.
