### ISSUE TITLE
max-w-none and svg flags

### ISSUE THREAD

**Issue by underdpt** [bezhanSalleh/filament-language-switch#73]
Hello,

When using svg flags, I've noticed that they're too big:

![imagen](https://github.com/bezhanSalleh/filament-language-switch/assets/8122137/24e93601-f3b5-40b9-8254-afd7ce080294)

This is due to `max-w-none` being used. I don't know what's the reason for this class, maybe it can be safely removed? I can submit a PR if needed.

**Comment by aurawindsurfing** [comment]
Just add 

```
h-8
```

after max-w-none and it will work as expected.

This is such a good package! @bezhanSalleh
