### ISSUE TITLE
Error: Type Error Occurs After Updating Filament to V3.2.2

### ISSUE THREAD

**Issue by danialRahimy** [bezhanSalleh/filament-language-switch#75]
After upgrading the filament to version 3.2.2, I encountered the following error:

![Screenshot from 2024-01-16 12-59-33](https://github.com/bezhanSalleh/filament-language-switch/assets/48244647/87a49239-68ea-4da1-9233-77457088a293)

**Comment by fsamapoor** [comment]
You need to upgrade the package and migrate from 2.x to 3.x.

Check out the readme file for the instructions and required steps.

**Comment by danialRahimy** [comment]
It works, thanks.
