### ISSUE TITLE
The switch breaks when I open the profile page

### ISSUE THREAD

**Issue by free-storage** [bezhanSalleh/filament-language-switch#81]
The switch breaks when I open the profile page

page url: http://localhost/app/profile

<img width="277" alt="image" src="https://github.com/bezhanSalleh/filament-language-switch/assets/52704675/ab677ac1-b8b5-4bfa-8d9a-774b3ce89ea7">
<img width="506" alt="image" src="https://github.com/bezhanSalleh/filament-language-switch/assets/52704675/57e5789b-75ff-42ae-9fc9-a86ba619db21">
<img width="454" alt="image" src="https://github.com/bezhanSalleh/filament-language-switch/assets/52704675/4b16efcc-4458-481b-93a3-43f6479f4af4">

There are no other plugins. Clean installation.

**Comment by free-storage** [comment]
Help!

**Comment by free-storage** [comment]
Solved a problem. 

If `$panel->profile(isSimple: false)` then you need to exclude this page from
```
$switch
->visible(outsidePanels: true)
->outsidePanelRoutes([
  'auth.login',
  'auth.register',
  'auth.password-reset',
])
```

**Comment by free-storage** [comment]
@bezhanSalleh bezhanSalleh Fix this problem. What's the problem with outside. The switch is superimposed on the profile.

**Comment by bezhanSalleh** [comment]
> @bezhanSalleh Fix this problem. What's the problem with outside. The switch is superimposed on the profile.

Sure, i will get right to it.
