### ISSUE TITLE
Problem with instaling in new Laravel 11 project

### ISSUE THREAD

**Issue by SebastianRajca** [bezhanSalleh/filament-language-switch#83]
I have a clean Laravel 11 project with clean FilamentPHP installed, I can't install filament-language-switch.
I get this error:

C:\laragon\www\testowy-projekt>composer require bezhansalleh/filament-language-switch
Using version ^3.0 for bezhansalleh/filament-language-switch
./composer.json has been updated
Running composer update bezhansalleh/filament-language-switch
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bezhansalleh/filament-language-switch ^3.0 -> satisfiable by bezhansalleh/filament-language-switch[3.0.0, ..., 3.0.5].
    - bezhansalleh/filament-language-switch[3.0.0, ..., 3.0.5] require illuminate/contracts ^9.0|^10.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bezhansalleh/filament-language-switch:*" to figure out if any version is installable, or "composer require bezhansalleh/filament-language-switch:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by SebastianRajca** [comment]
My composer require section:

    "require": {
        "php": "^8.2",
        "filament/filament": "^3.2",
        "laravel/framework": "^11.0",
        "laravel/tinker": "^2.9"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "phpunit/phpunit": "^10.5",
        "spatie/laravel-ignition": "^2.4"

**Comment by Mahdi-Sahib** [comment]
same here

**Comment by lloricode** [comment]
see #82
