### ISSUE TITLE
compatibility with laravel 11

### ISSUE THREAD

**Issue by Mahdi-Sahib** [bezhanSalleh/filament-language-switch#84]
Issues when run install by composer and get this error 

  Problem 1
    - bezhansalleh/filament-language-switch[v0.0.0, ..., v0.0.1, v1.0.0, ..., 1.0.8] require filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.55] but it conflicts with your root composer.json require (^3.2).
    - bezhansalleh/filament-language-switch[2.0.0, ..., 2.0.1, 3.0.0, ..., 3.0.5] require illuminate/contracts ^9.0|^10.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bezhansalleh/filament-language-switch * -> satisfiable by bezhansalleh/filament-language-switch[v0.0.0, v0.0.1, v1.0.0, ..., 1.0.8, 2.0.0, 2.0.1, 3.0.0, ..., 3.0.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require bezhansalleh/filament-language-switch:*" to figure out if any version is installable, or "composer require bezhansalleh/filament-language-switch:^2.1" if you know which you need.

**Comment by free-storage** [comment]
Me too. Fix please

**Comment by lloricode** [comment]
see #82
