### ISSUE TITLE
Carbon locale shouldn't be set

### ISSUE THREAD

**Issue by ManuDoni** [bezhanSalleh/filament-language-switch#9]
The carbon locale is working, but because of a carbon service provider, not thanks to this package.

https://github.com/bezhanSalleh/filament-language-switch/blob/1a5bc18545d8791190c72ef7ec72780b91b2c2ac/src/Http/Middleware/SwitchLanguageLocale.php#L25

This should be:
```php
if (config('filament-language-switch.carbon')) { 
```
But the Carbon package registers a listener that sets the locale to all carbon classes, when the laravel locale changes, in a service provider.

You can find it in `vendor/nesbot/carbon/src/Carbon/Laravel/ServiceProvider.php`

I think that it is all working but the `filament-language-switch.carbon` config should be removed

**Comment by bezhanSalleh** [comment]
tnx.
