### ISSUE TITLE
outside panel placement always pointing to left side (top, bottom) only

### ISSUE THREAD

**Issue by valpuia604** [bezhanSalleh/filament-language-switch#90]
This is my code inside `AppServiceProvider`
```php
public function boot(): void
{
    LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
        $switch
            ->locales(['en', 'zh_CN'])
            ->visible(outsidePanels: true)
            ->outsidePanelPlacement(Placement::TopCenter);
    });
}
```
And this is the result. No matter how I try to change the position, it always ended up to `TopLeft` or `BottomLeft` only

![Screenshot from 2024-04-09 10-36-17](https://github.com/bezhanSalleh/filament-language-switch/assets/141896542/ee95d4e3-50f8-4b73-b95d-497ed73279a6)

Laravel `v11.2.0`
Livewire `v3.4.10`
Filament `v3.2.63`
Language switch `v3.1.0`

**Comment by stardust-kevin** [comment]
I think you can just do this:

**Comment by bezhanSalleh** [comment]
simple pages do not have render hooks in the topbar so the placement seems kinda off. any help would be appreciated

**Comment by buzkall** [comment]
Maybe the hooks PanelsRenderHook::AUTH_LOGIN_FORM_AFTER, PanelsRenderHook::AUTH_PASSWORD_RESET_REQUEST_FORM_BEFORE and PanelsRenderHook::AUTH_REGISTER_FORM_BEFORE can be used.

I've done it setting the showOutsidePanels to false, and adding the following to my AppServiceProvider. 
(with the hack of the mx-auto to center it or the selected language will appear left and dropdown will appear in the center of the form)

```
      FilamentView::registerRenderHook(
          PanelsRenderHook::AUTH_LOGIN_FORM_BEFORE,
          fn(): string => Blade::render('<div class="mx-auto">@livewire(\'filament-language-switch\')</div>'),
      );

      FilamentView::registerRenderHook(
          PanelsRenderHook::AUTH_PASSWORD_RESET_REQUEST_FORM_BEFORE,
          fn(): string => Blade::render('<div class="mx-auto">@livewire(\'filament-language-switch\')</div>'),
      );
```

**Comment by haggaiwambua** [comment]
> [@valpuia604](https://github.com/valpuia604) I solved this problem, hope it helps you. Laravel `v11.0.9` Filament `v3.2.81` Language switch `v3.1` ![image](https://github.com/bezhanSalleh/filament-language-switch/assets/69184595/0ba32112-b339-4f79-b01c-ad8ec4b92f56) I think you can just do this:
> 
> > /vendor/bezhansalleh/filament-language-switch/resources/views/language-switch.blade.php
> 
> replace `'justify-end' => str_contains($outsidePanelsPlacement, 'right'),` with `'right-0' => str_contains($outsidePanelsPlacement, 'right'),` If your theme does not have the `right-0` attribute, you need to customize the theme and add it.
> 
> ```
> .right-0 {
>     right: 0px;
> }
> ```
> 
> Now, it works great.

This works great!

**Comment by rtrudel** [comment]
Same problem here, solution above seems a good one, but I do not want to edit vendor files. Any idea if this can be fixed with a plugin update soon?

**Comment by haggaiwambua** [comment]
@rtrudel Publish the views using `php artisan vendor:publish --tag="filament-language-switch-views" then edit the /resources/views/vendor/bezhansalleh/filament-language-switch/resources/views/language-switch.blade.php.
`

**Comment by rtrudel** [comment]
It works! Thanks.

I added the style right there too as I do not use custom theme.

```html
<div>
   /** code here

   <style>
        .right-0 {
            right: 0;
        }
   </style>
</div>
```

This is to me a workaround, can we hope this may be included in an update?
