### ISSUE TITLE
Place switch inside user menu

### ISSUE THREAD

**Issue by diazwatson** [bezhanSalleh/filament-language-switch#92]
I am opening this here as the question link redirects me to a 404 page for some reason.

Is there a way to place the switch inside the user's menu as an extra option of even inside the user profile form to let users set their default language?

![Screenshot 2024-04-11 at 14 09 42](https://github.com/bezhanSalleh/filament-language-switch/assets/1080386/6d3b84b3-fc5b-463d-9008-892db49a678b)

**Comment by JohnnyEvo** [comment]
You can set `renderHook` :

```php
        LanguageSwitch::configureUsing(function (LanguageSwitch $switch) {
            $switch->renderHook(PanelsRenderHook::USER_MENU_PROFILE_AFTER)
        });
```
