### ISSUE TITLE
Some translate are wrong due to unicode issue !

### ISSUE THREAD

**Issue by Khant-Nyar** [bezhanSalleh/filament-language-switch#99]
![image](https://github.com/bezhanSalleh/filament-language-switch/assets/61083917/83d5e673-a51f-4425-acad-48863e5b1f7e)

in the figure it should be "Product Category ကိုတည်းဖြတ်ပါ ။"  it just an example 
as the native speaking of Myanmar (burmese) need to edit a lot of that labels 
 
 and also breadcrumbs arrow is reverse in Myanmar language

**Comment by bezhanSalleh** [comment]
no a plugin issue, submit the translations or fix to the filamentphp repo itself.
